name: "Update readme with issues"

on:
  workflow_dispatch:
  issues:
      types: ['opened', 'edited', 'closed']
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: rewriteReadme
      uses: seed-of-apricot/issue-list-readme@v1.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: add-and-commit
      uses: EndBug/add-and-commit@v4
      with:
       message: README.md has been re-written
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: push
      uses: ad-m/github-push-action@master
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
